name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publishing:
    name: Building & Publish
    runs-on: ubuntu-20.04
    if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.HIGH5_BOT_TOKEN }}
      - name: Configuring Git and NPM
        run: |
          git config --global user.name "high5-bot"
          git config --global user.email "me+high5@dunklestoast.de"
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.HIGH5_NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Installing dependencies
        run: npm i
      - name: Release It
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.HIGH5_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.HIGH5_NPM_TOKEN }}
